FROM mcr.microsoft.com/dotnet/sdk:8.0

WORKDIR /app
COPY . .

RUN dotnet tool install --global dotnet-ef
ENV PATH="$PATH:/root/.dotnet/tools"

ENTRYPOINT ["dotnet", "ef", "database", "update", \
  "--project", "MajorExpress.Delivery.Infrastructure", \
  "--startup-project", "MajorExpress.Delivery.Api", \
  "--context", "ApplicationDbContext"]