// <auto-generated />
using System;
using MajorExpress.Delivery.Infrastructure.Adapters.Postgres;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MajorExpress.Delivery.Infrastructure.Adapters.Postgres.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250718190305_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MajorExpress.Delivery.Domain.Models.Cargo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Size")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Cargos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("72a0b771-9caf-41ca-b1e5-142c3a584cc6"),
                            Description = "Компьютер",
                            Size = 90m,
                            Weight = 5m
                        },
                        new
                        {
                            Id = new Guid("b8ab0ba0-6067-4b85-abc8-be3236d40a78"),
                            Description = "Стол",
                            Size = 360m,
                            Weight = 7m
                        },
                        new
                        {
                            Id = new Guid("14a3d5b1-fbc6-4300-8d5f-42ad13f5bfb9"),
                            Description = "Кресло",
                            Size = 240m,
                            Weight = 25m
                        },
                        new
                        {
                            Id = new Guid("73b3dcd2-9fd9-427e-9257-29c5f28cea5e"),
                            Description = "Шкаф",
                            Size = 600m,
                            Weight = 50m
                        });
                });

            modelBuilder.Entity("MajorExpress.Delivery.Domain.Models.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d5f3f9f7-8d6c-4100-aecf-4af6e4969eb2"),
                            UserId = new Guid("23244377-d294-46b4-9245-5df4af5d1d9f")
                        },
                        new
                        {
                            Id = new Guid("f5cea0f2-1bc8-402f-9e02-7e4512de4fea"),
                            UserId = new Guid("0eaa9e2a-eed0-4619-946c-aa91c320210e")
                        },
                        new
                        {
                            Id = new Guid("e6ca25f2-6691-410e-8c1b-7be47b109995"),
                            UserId = new Guid("37fce3f7-3c45-4117-a88d-204c2e931a76")
                        },
                        new
                        {
                            Id = new Guid("e83ccf84-dc67-45fd-8fb7-6d82b5319ee8"),
                            UserId = new Guid("f23f844b-ffe5-4c13-9be0-78997c289de8")
                        });
                });

            modelBuilder.Entity("MajorExpress.Delivery.Domain.Models.Courier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Couriers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("83108fb9-1177-4d2e-ae59-6b4c86b014ba"),
                            UserId = new Guid("5b453a8e-c239-42ed-8b2d-ac04ce43c33b")
                        },
                        new
                        {
                            Id = new Guid("95420664-aa3c-45bc-8170-2f60c4d8f697"),
                            UserId = new Guid("e1a1daf4-0f83-4358-919d-75c9c34280bf")
                        },
                        new
                        {
                            Id = new Guid("68a6a604-2b38-4376-95f9-b06652543e05"),
                            UserId = new Guid("166a99b2-7ed0-4b41-87fb-affbda39119d")
                        },
                        new
                        {
                            Id = new Guid("ef391859-a5cc-4b04-aa7e-c43d8d8ef2f5"),
                            UserId = new Guid("6124c5dd-155e-453a-90d7-401f08b8f376")
                        });
                });

            modelBuilder.Entity("MajorExpress.Delivery.Domain.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("CancelComment")
                        .HasColumnType("text");

                    b.Property<Guid>("CargoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CourierId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PickupAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PickupTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CargoId");

                    b.HasIndex("ClientId");

                    b.HasIndex("CourierId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22a11daa-7534-4d0f-ab6b-766a4ac855f0"),
                            CargoId = new Guid("72a0b771-9caf-41ca-b1e5-142c3a584cc6"),
                            ClientId = new Guid("d5f3f9f7-8d6c-4100-aecf-4af6e4969eb2"),
                            CourierId = new Guid("83108fb9-1177-4d2e-ae59-6b4c86b014ba"),
                            CreatedAt = new DateTime(2025, 7, 10, 7, 20, 0, 0, DateTimeKind.Utc),
                            DeliveryAddress = "Адрес выгрузки 0",
                            PickupAddress = "Адрес погрузки 0",
                            PickupTime = new DateTime(2025, 7, 24, 14, 40, 0, 0, DateTimeKind.Utc),
                            Status = "Новая"
                        },
                        new
                        {
                            Id = new Guid("bb3d699a-381c-49db-a97f-a87cc55d7325"),
                            CargoId = new Guid("b8ab0ba0-6067-4b85-abc8-be3236d40a78"),
                            ClientId = new Guid("f5cea0f2-1bc8-402f-9e02-7e4512de4fea"),
                            CourierId = new Guid("95420664-aa3c-45bc-8170-2f60c4d8f697"),
                            CreatedAt = new DateTime(2025, 7, 11, 8, 21, 0, 0, DateTimeKind.Utc),
                            DeliveryAddress = "Адрес выгрузки 1",
                            PickupAddress = "Адрес погрузки 1",
                            PickupTime = new DateTime(2025, 7, 25, 15, 41, 0, 0, DateTimeKind.Utc),
                            Status = "Передано на выполнение"
                        },
                        new
                        {
                            Id = new Guid("eef68d46-5959-422f-b782-09722c4d483f"),
                            CargoId = new Guid("14a3d5b1-fbc6-4300-8d5f-42ad13f5bfb9"),
                            ClientId = new Guid("e6ca25f2-6691-410e-8c1b-7be47b109995"),
                            CourierId = new Guid("68a6a604-2b38-4376-95f9-b06652543e05"),
                            CreatedAt = new DateTime(2025, 7, 12, 9, 22, 0, 0, DateTimeKind.Utc),
                            DeliveryAddress = "Адрес выгрузки 2",
                            PickupAddress = "Адрес погрузки 2",
                            PickupTime = new DateTime(2025, 7, 26, 16, 42, 0, 0, DateTimeKind.Utc),
                            Status = "Выполнено"
                        },
                        new
                        {
                            Id = new Guid("d51b4b9e-0e70-4e9c-82c1-c96c69c1c769"),
                            CancelComment = "Тест",
                            CargoId = new Guid("73b3dcd2-9fd9-427e-9257-29c5f28cea5e"),
                            ClientId = new Guid("e83ccf84-dc67-45fd-8fb7-6d82b5319ee8"),
                            CourierId = new Guid("ef391859-a5cc-4b04-aa7e-c43d8d8ef2f5"),
                            CreatedAt = new DateTime(2025, 7, 13, 10, 23, 0, 0, DateTimeKind.Utc),
                            DeliveryAddress = "Адрес выгрузки 3",
                            PickupAddress = "Адрес погрузки 3",
                            PickupTime = new DateTime(2025, 7, 27, 17, 43, 0, 0, DateTimeKind.Utc),
                            Status = "Отменена"
                        });
                });

            modelBuilder.Entity("MajorExpress.Delivery.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Patronymic")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("23244377-d294-46b4-9245-5df4af5d1d9f"),
                            FirstName = "Вера",
                            LastName = "Сияносова",
                            Patronymic = "Прокловна",
                            PhoneNumber = "+7 (978) 409-31-96"
                        },
                        new
                        {
                            Id = new Guid("0eaa9e2a-eed0-4619-946c-aa91c320210e"),
                            FirstName = "Гавриил",
                            LastName = "Кушкин",
                            Patronymic = "Николаевич",
                            PhoneNumber = "+7 (970) 422-97-49"
                        },
                        new
                        {
                            Id = new Guid("37fce3f7-3c45-4117-a88d-204c2e931a76"),
                            FirstName = "Филипп",
                            LastName = "Кулатов",
                            Patronymic = "Маркович",
                            PhoneNumber = "+7 (959) 964-23-76"
                        },
                        new
                        {
                            Id = new Guid("f23f844b-ffe5-4c13-9be0-78997c289de8"),
                            FirstName = "Тимофей",
                            LastName = "Кинжаев",
                            Patronymic = "Николаевич",
                            PhoneNumber = "+7 (913) 161-14-77"
                        },
                        new
                        {
                            Id = new Guid("5b453a8e-c239-42ed-8b2d-ac04ce43c33b"),
                            FirstName = "Ева",
                            LastName = "Батурина",
                            Patronymic = "Афанасьевна",
                            PhoneNumber = "+7 (974) 364-82-60"
                        },
                        new
                        {
                            Id = new Guid("e1a1daf4-0f83-4358-919d-75c9c34280bf"),
                            FirstName = "Людмила",
                            LastName = "Уттеркло",
                            Patronymic = "Тимофеевна",
                            PhoneNumber = "+7 (921) 346-18-59"
                        },
                        new
                        {
                            Id = new Guid("166a99b2-7ed0-4b41-87fb-affbda39119d"),
                            FirstName = "Александра",
                            LastName = "Дудко",
                            Patronymic = "Егоровна",
                            PhoneNumber = "+7 (936) 742-93-76"
                        },
                        new
                        {
                            Id = new Guid("6124c5dd-155e-453a-90d7-401f08b8f376"),
                            FirstName = "Савва",
                            LastName = "Ярошевский",
                            Patronymic = "Петрович",
                            PhoneNumber = "+7 (953) 595-58-95"
                        });
                });

            modelBuilder.Entity("MajorExpress.Delivery.Domain.Models.Client", b =>
                {
                    b.HasOne("MajorExpress.Delivery.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MajorExpress.Delivery.Domain.Models.Courier", b =>
                {
                    b.HasOne("MajorExpress.Delivery.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MajorExpress.Delivery.Domain.Models.Order", b =>
                {
                    b.HasOne("MajorExpress.Delivery.Domain.Models.Cargo", "Cargo")
                        .WithMany()
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MajorExpress.Delivery.Domain.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MajorExpress.Delivery.Domain.Models.Courier", "Courier")
                        .WithMany()
                        .HasForeignKey("CourierId");

                    b.Navigation("Cargo");

                    b.Navigation("Client");

                    b.Navigation("Courier");
                });
#pragma warning restore 612, 618
        }
    }
}
